# Exploratory Data Analysis (EDA)

### Used libraries:

In [23]:
import polars as pl
import kagglehub
from pathlib import Path
import shutil
from tqdm import tqdm

### 1. Data ingestion

In [ ]:
dataset = "elemento/nyc-yellow-taxi-trip-data"
file = "yellow_tripdata_2015-01.csv"
bronze_path = Path().cwd().parent / "data" / "bronze" / file

if not bronze_path.exists():
    dataset_path = Path(kagglehub.dataset_download(dataset, file))
    shutil.copy(dataset_path, bronze_path)

In [9]:
lf = pl.scan_csv(bronze_path)
lf.head(10).collect()

shape: (10, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ tip_amoun ┆ tolls_amo ┆ improveme ┆ total_amo │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ t         ┆ unt       ┆ nt_surcha ┆ unt       │
│ i64      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ rge       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ str       ┆ str       ┆           ┆   ┆           ┆           ┆ f64       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 3.25      ┆ 0.0       ┆ 0.3       ┆ 17.05     │
│          ┆ 5         ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:05:39  ┆ 19:23:42  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 2.0       ┆ 0.0       ┆ 0.3       ┆ 17.8      │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:33:38  ┆ 20:53:28  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.3       ┆ 10.8      │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:33:38  ┆ 20:43:41  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.3       ┆ 4.8       │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:33:39  ┆ 20:35:31  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.3       ┆ 16.3      │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:33:39  ┆ 20:52:58  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 6.7       ┆ 5.33      ┆ 0.3       ┆ 40.33     │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:33:39  ┆ 20:53:52  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.3       ┆ 15.3      │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:33:39  ┆ 20:58:31  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-1 ┆ 2015-01-1 ┆ 3         ┆ … ┆ 1.66      ┆ 0.0       ┆ 0.3       ┆ 9.96      │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:33:39  ┆ 20:42:20  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-1 ┆ 2015-01-1 ┆ 3         ┆ … ┆ 0.0       ┆ 5.33      ┆ 0.3       ┆ 58.13     │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:33:39  ┆ 21:11:35  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2015-01-1 ┆ 2015-01-1 ┆ 2         ┆ … ┆ 1.55      ┆ 0.0       ┆ 0.3       ┆ 9.35      │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 20:33:40  ┆ 20:40:44  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### 2. Initial diagnosis

In [12]:
numeric_columns = [
    "passenger_count",
    "trip_distance",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount"
]

lf.select(numeric_columns).describe()

shape: (9, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ passenger ┆ trip_dist ┆ fare_amou ┆ … ┆ tip_amoun ┆ tolls_amo ┆ improveme ┆ total_am │
│ ---       ┆ _count    ┆ ance      ┆ nt        ┆   ┆ t         ┆ unt       ┆ nt_surcha ┆ ount     │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ rge       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 1.2748986 ┆ 1.2748986 ┆ 1.2748986 ┆ … ┆ 1.2748986 ┆ 1.2748986 ┆ 1.2748983 ┆ 1.274898 │
│           ┆ e7        ┆ e7        ┆ e7        ┆   ┆ e7        ┆ e7        ┆ e7        ┆ 6e7      │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 3.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1.681491  ┆ 13.45913  ┆ 11.905659 ┆ … ┆ 1.853814  ┆ 0.243498  ┆ 0.283143  ┆ 15.10829 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ std       ┆ 1.337924  ┆ 9844.0942 ┆ 10.302537 ┆ … ┆ 1106.4323 ┆ 1.527171  ┆ 0.069086  ┆ 1106.503 │
│           ┆           ┆ 18        ┆           ┆   ┆ 14        ┆           ┆           ┆ 247      │
│ min       ┆ 0.0       ┆ 0.0       ┆ -450.0    ┆ … ┆ -92.42    ┆ -26.0     ┆ 0.0       ┆ -450.3   │
│ 25%       ┆ 1.0       ┆ 1.0       ┆ 6.5       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.3       ┆ 8.16     │
│ 50%       ┆ 1.0       ┆ 1.68      ┆ 9.0       ┆ … ┆ 1.0       ┆ 0.0       ┆ 0.3       ┆ 11.16    │
│ 75%       ┆ 2.0       ┆ 3.0       ┆ 13.5      ┆ … ┆ 2.06      ┆ 0.0       ┆ 0.3       ┆ 16.3     │
│ max       ┆ 9.0       ┆ 1.5420e7  ┆ 4008.0    ┆ … ┆ 3950588.8 ┆ 1450.09   ┆ 0.3       ┆ 3950611. │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### 3. Data transformation

In [39]:
df_silver = (
    lf.filter(pl.col("fare_amount") >= 0)
    .filter(pl.col("extra") >= 0)
    .filter(pl.col("mta_tax") >= 0)
    .filter(pl.col("tip_amount") >= 0)
    .filter(pl.col("tolls_amount") >= 0)
    .filter(pl.col("total_amount") >= 0)
    .with_columns(
        pl.col("tpep_pickup_datetime").str.to_datetime().alias("tpep_pickup_datetime"),
        pl.col("tpep_dropoff_datetime").str.to_datetime().alias("tpep_dropoff_datetime")
    )
    .rename({
        "VendorID": "vendor_id",
        "RateCodeID": "rate_code_id"
    })
    .collect()
)

bronze_size = lf.select(pl.len()).collect().item()
silver_size = df_silver.shape[0]

print(f"Bronze size: {bronze_size}")
print(f"Silver size: {silver_size}")
print(f"Rows affected: {bronze_size - silver_size}")

Bronze size: 12748986
Silver size: 12744911
Rows affected: 4075

In [40]:
df_silver.head()

shape: (5, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ vendor_id ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ tip_amoun ┆ tolls_amo ┆ improveme ┆ total_am │
│ ---       ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ t         ┆ unt       ┆ nt_surcha ┆ ount     │
│ i64       ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ rge       ┆ ---      │
│           ┆ ---       ┆ ---       ┆ i64       ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆ f64       ┆          │
│           ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2         ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 3.25      ┆ 0.0       ┆ 0.3       ┆ 17.05    │
│           ┆ 5         ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 19:05:39  ┆ 19:23:42  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 2.0       ┆ 0.0       ┆ 0.3       ┆ 17.8     │
│           ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:33:38  ┆ 20:53:28  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.3       ┆ 10.8     │
│           ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:33:38  ┆ 20:43:41  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.3       ┆ 4.8      │
│           ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:33:39  ┆ 20:35:31  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆ 2015-01-1 ┆ 2015-01-1 ┆ 1         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.3       ┆ 16.3     │
│           ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ 20:33:39  ┆ 20:52:58  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### 4. Silver data loading

In [38]:
silver_path = Path().cwd().parent / "data" / "silver" / bronze_path.with_suffix(".parquet").name

df_silver.write_parquet(silver_path)